services:
  asterisk:
    image: andrius/asterisk:latest
    container_name: asterisk
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "5060:5060/udp"    # SIP
      - "8088:8088"        # ARI HTTP/WebSocket
      - "10000-10100:10000-10100/udp"  # RTP
    volumes:
      - ./asterisk/conf:/etc/asterisk
      - ./asterisk/sounds:/var/lib/asterisk/sounds/custom
    environment:
      - TZ=Europe/Moscow
